version: 2
updates:
  # Python dependencies
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'python'
    commit-message:
      prefix: 'deps'
      prefix-development: 'deps-dev'
    pull-request-branch-name:
      separator: '/'
    groups:
      # Group all patch and minor updates together
      python-patches:
        patterns:
          - '*'
        update-types:
          - 'patch'
          - 'minor'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
    groups:
      # Group all GitHub Actions updates together
      actions:
        patterns:
          - '*'
