extends: default

rules:
  line-length:
    max: 100
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    min-spaces-from-content: 2
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
  document-start: disable
  empty-lines:
    max: 2
