#!/bin/sh
set -e

case "$1" in
remove | upgrade | deconfigure)
	# Services handled by dh_installsystemd
	
	# Clean up Avahi service file
	rm -f /etc/avahi/services/distiller-wifi.service
	;;

failed-upgrade)
	;;

*)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0