#!/bin/sh
set -e

case "$1" in
remove | upgrade | deconfigure)
	[ -f /etc/avahi/services/distiller-wifi.service ] &&
		rm -f /etc/avahi/services/distiller-wifi.service
	;;

failed-upgrade) ;;

*)
	echo "ERROR: prerm called with unknown argument: $1" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
